### ISSUE TITLE
regression in 3.14.0 release

### ISSUE THREAD

**Issue by ngothan** [opencryptoki/opencryptoki#299]
@p-steuer , Hi Patrick
With new opencryptoki-3.14.0 we see a segfault when running following command line on x86_64 test machine with rhel-8.3.0 snapshot.
  pkcsconf -P -c0 -S 87654321 -n 84756352

The backtrace to the crash
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff3f291a4 in token_specific_rng (tokdata=tokdata@entry=0x0, 
    output=output@entry=0x7fffffffd880 "\235\025\226\034\032Y/\330{\204\365\210\341\313\263\t\235\025\226\034\032Y/\330{\204\365\210\341\313\263\t\367\270W\\\2 bytes=bytes@entry=32) at usr/lib/tpm_stdll/tpm_specific.c:156
156     {
(gdb) bt
#0  0x00007ffff3f291a4 in token_specific_rng (tokdata=tokdata@entry=0x0, 
    output=output@entry=0x7fffffffd880 "\235\025\226\034\032Y/\330{\204\365\210\341\313\263\t\235\025\226\034\032Y/\330{\204\365\210\341\313\263\t\367\270W\\\2 bytes=bytes@entry=32) at usr/lib/tpm_stdll/tpm_specific.c:156
#1  0x00007ffff3f30ff3 in openssl_gen_key () at usr/lib/tpm_stdll/tpm_openssl.c:69
#2  0x00007ffff3f2daaf in token_create_public_tree (tokdata=tokdata@entry=0x5555557647b0, 
    pinHash=pinHash@entry=0x7fffffffdb80 "@\037\357\260t5v\374z\035WF\235\317\225\331Z\322\341\317", pPin=pPin@entry=0x5555557612e0 "84756352")
    at usr/lib/tpm_stdll/tpm_specific.c:1470
#3  0x00007ffff3f2f333 in token_specific_set_pin (tokdata=0x5555557647b0, sess=0x55555576d850, pOldPin=0x5555557612c0 "87654321", ulOldPinLen=<optimized out>, 
    pNewPin=0x5555557612e0 "84756352", ulNewPinLen=8) at usr/lib/tpm_stdll/tpm_specific.c:2256
#4  0x00007ffff3edfbc5 in SC_SetPIN (tokdata=0x5555557647b0, sSession=0x7fffffffddb0, pOldPin=0x5555557612c0 "87654321", ulOldLen=8, pNewPin=0x5555557612e0 "84
    ulNewLen=8) at usr/lib/common/new_host.c:710
#5  0x00007ffff4d76dd8 in C_SetPIN (ulNewLen=8, pNewPin=0x5555557612e0 "84756352", ulOldLen=8, pOldPin=0x5555557612c0 "87654321", hSession=1)
    at usr/lib/api/api_interface.c:3292
#6  C_SetPIN (hSession=1, pOldPin=0x5555557612c0 "87654321", ulOldLen=8, pNewPin=0x5555557612e0 "84756352", ulNewLen=8) at usr/lib/api/api_interface.c:3256
#7  0x000055555555aeb1 in set_user_pin (slot_id=<optimized out>, user=0, oldpin=0x5555557612c0 "87654321", newpin=0x5555557612e0 "84756352")
    at usr/sbin/pkcsconf/pkcsconf.c:1097
#8  0x00005555555577b8 in main (argc=7, argv=<optimized out>) at usr/sbin/pkcsconf/pkcsconf.c:330
```

I also attach detailed backtrace:
[opencryptoki-3.14.0-crash.txt](https://github.com/opencryptoki/opencryptoki/files/4681270/opencryptoki-3.14.0-crash.txt)

Thank you so much,
Than

**Comment by p-steuer** [comment]
Hi Than,

thanks for reporting.

PR #300 fixes the issue.

**Comment by ngothan** [comment]
Hi Patrick, Ingo
i tested the fix and confirmed that the crash is gone. Thank you so much for quick solution :)

Than
